"""HTTP client module for TrainingPeaks API."""

from tp_mcp.client.cache import (
    CachedEntry,
    CacheTier,
    ResponseCache,
    build_cache_key,
)
from tp_mcp.client.http import (
    APIError,
    APIResponse,
    AuthenticationError,
    ErrorCode,
    NotFoundError,
    RateLimitError,
    RawResponse,
    TPClient,
)
from tp_mcp.client.models import (
    AnalysisChannel,
    AnalysisTotal,
    PeakData,
    PeaksResponse,
    UserProfile,
    WorkoutAnalysis,
    WorkoutDetail,
    WorkoutInterval,
    WorkoutStructure,
    WorkoutSummary,
    parse_user_profile,
    parse_workout_analysis,
    parse_workout_detail,
    parse_workout_list,
    parse_workout_summary,
)

__all__ = [
    "APIError",
    "APIResponse",
    "AnalysisChannel",
    "AnalysisTotal",
    "AuthenticationError",
    "CachedEntry",
    "CacheTier",
    "ErrorCode",
    "NotFoundError",
    "PeakData",
    "PeaksResponse",
    "RateLimitError",
    "RawResponse",
    "ResponseCache",
    "TPClient",
    "build_cache_key",
    "UserProfile",
    "WorkoutAnalysis",
    "WorkoutDetail",
    "WorkoutInterval",
    "WorkoutStructure",
    "WorkoutSummary",
    "parse_user_profile",
    "parse_workout_analysis",
    "parse_workout_detail",
    "parse_workout_list",
    "parse_workout_summary",
]
